/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData behance = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData card_collection = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData bar_feed = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData first_meet = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData group_8 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData group_9 = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData group_10 = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData group_15 = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData group_16 = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData group_18 = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData group_19 = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData group_20 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData group_21 = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData group_48 = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData group_56 = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData group_65 = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData group_65_2 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData group_82 = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData group_140 = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData group_570 = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData group_647 = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData group_647_2 = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData group_651 = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData group_663 = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData group_1047 = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData group_1073 = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData group_1113 = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData group_1174 = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData insta = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData path_237 = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData group_11 = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData group_12 = const IconData(0xe824, fontFamily: _kFontFam);
}
